[program:reverb]
process_name=%(program_name)s
command=php /app/artisan reverb:start
user=www-data
autostart=true
autorestart=true
startsecs=10
stopasgroup=true
killasgroup=true
numprocs=1
priority=999
redirect_stderr=true
stdout_logfile=/app/storage/logs/reverb.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10