services:
  laravel:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: nextplay-dev-laravel
    restart: unless-stopped
    volumes:
      - ./:/app
    networks:
      - nextplay-dev-back
    depends_on:
      - db
    ports:
      - "80:8000"

  db:
    image: postgres:latest
    env_file:
      - .env
    container_name: nextplay-dev-db
    restart: unless-stopped
    networks:
      - nextplay-dev-back
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: api
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - nextplay-postgres:/var/lib/postgresql/data
      - ./docker/dev/sql:/docker-entrypoint-initdb.d:ro

  mailpit:
    image: axllent/mailpit
    container_name: nextplay-dev-mailpit
    restart: unless-stopped
    networks:
      - nextplay-dev-back
    volumes:
      - mailpit-data:/data
    ports:
      - 8025:8025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

networks:
  nextplay-dev-back:
    driver: bridge

volumes:
  nextplay-postgres:
  mailpit-data:
